### ISSUE TITLE
Not working for angular 5

### ISSUE THREAD

**Issue by Kalpesh300** [NejcZdovc/ng2-select2-demo#10]
I am currently working on my Angular-5 project. I installed package using command : 
npm i -S ng2-select2
In my html page and my component file I am using same syntax which you used in your multiple demo.
But somehow it is not working.
I also downloaded select2.full.js and included it in .angular.cli.json file.
Do I need to anything more?

**Comment by NejcZdovc** [comment]
@Kalpesh300 which version of the ng2-select2 are you using? and what particular is not working? can you paste some screen shot maybe?

**Comment by Kalpesh300** [comment]
I don't know the version, but I installed this package using npm by following the link: https://github.com/NejcZdovc/ng2-select2 

Actually, I want to implement multiple selection dropdown.
Following is my html code:
` <select2 [data]="exampleData"
        [options]="options"
        [width]="500"
        [value]="value"
></select2>`

My component file:
 `constructor() {
   this.exampleData = [
      {
        id: 'multiple1',
        text: 'Multiple 1'
      },
      {
        id: 'multiple2',
        text: 'Multiple 2'
      },
      {
        id: 'multiple3',
        text: 'Multiple 3'
      },
      {
        id: 'multiple4',
        text: 'Multiple 4'
      }
    ];

    this.value = ['multiple2', 'multiple4'];

    this.options2 = {
      multiple: true
    };

    this.current = this.value.join(' | ');
  }`

My script property in .angular.cli.json:
   "scripts": [
        "../node_modules/platform/platform.js",
        "../node_modules/jquery/dist/jquery.min.js",
        "../src/scripts/select2.full.js",
        "../node_modules/jquery-slim/dist/jquery.slim.min.js",
        "../node_modules/bootstrap/dist/js/bootstrap.min.js",
        "../node_modules/popper.js/dist/umd/popper.js"

**Comment by NejcZdovc** [comment]
@Kalpesh300 with the latest version we switched cssImport to off, because people like to add it by them self. So if you are not adding css on you own please add cssImport tag like here https://github.com/NejcZdovc/ng2-select2-demo/blob/master/src/app/demos/basic/basic.component.html#L3

**Comment by Kalpesh300** [comment]
It is working. Thanks. But can I change css classes according to my need? If yes, then how to do that?

**Comment by NejcZdovc** [comment]
Not sure that I follow. Which classes?

**Comment by Kalpesh300** [comment]
anything for dropdown and selected values

**Comment by NejcZdovc** [comment]
well, this package is just a wrapper for select2 so please check https://github.com/select2/select2-bootstrap-theme no how to do it. Basically you can download existing select2 themes or create your own.
