### ISSUE TITLE
Thanks and I have a question

### ISSUE THREAD

**Issue by tosehee75** [NejcZdovc/ng2-select2-demo#5]
Thanks a bunch for this. I've been searching for select2 equivalent, and it seems that this is IT!

I tried a few options and it works for the most part. With that said, can you help me out with one issue I am running into?

I want to pre-populate the list with [value]. For some reason, this works when the [data] is a simply text array.

However, using your example where the values are below, it's not working.
```

 this.exampleData = [
      {
        id: 'basic1',
        text: 'Basic 1'
      },
      {
        id: 'basic2',
        disabled: true,
        text: 'Basic 2'
      },
      {
        id: 'basic3',
        text: 'Basic 3'
      },
      {
        id: 'basic4',
        text: 'Basic 4'
      }
    ];
```

In above case, how can I configure the <select2> so it [value] can be pre-populated based on the value of 'id' or 'text' other than a simple text array?

**Comment by diegodesouza** [comment]
@tosehee75 I've tested with your data locally and it's working ok for me, 

.html
```
     <select2 [data]="dummyData"
             [(ngModel)]="dummyModel"
             (valueChanged)="dummyModel = $event.value"
             [value]="dummyModel"
             [options]="options"
             ngDefaultControl>
    </select2>
```

.ts
```
   public dummyModel: string = '';
   public dummyData = [
    {
      'id': 'basic1',
      'text': 'Basic 1'
    },
    {
      'id': 'basic2',
      'disabled': true,
      'text': 'Basic 2'
    },
    {
      'id': 'basic3',
      'text': 'Basic 3'
    },
    {
      'id': 'basic4',
      'text': 'Basic 4'
    }
  ];
```

You may disregard the extra model, valueChanged, value, ngDefaultControl there.

**Comment by NejcZdovc** [comment]
seams like this is explained
