### ISSUE TITLE
not working for me 

### ISSUE THREAD

**Issue by somnathswami** [NejcZdovc/ng2-select2-demo#6]
I implement same example for me but it wont work it gives message in console 
"Please add Select2 library (js file) to the project. You can download it from https://github.com/select2/select2/tree/master/dist/js."

**Comment by NejcZdovc** [comment]
I presume that you are using angular 4. You need to include the full version. More info here https://github.com/NejcZdovc/ng2-select2/issues/77

**Comment by somnathswami** [comment]
got it I just need to add js files to my project and needs to be add it in angiular-cli.json file

**Comment by asongkai** [comment]
@somnathswami could you show me how please?

**Comment by somnathswami** [comment]
Sorry..! currently not having that code to show you
